name: Sync labels

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  labels:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: srealmoreno/label-sync-action@v1
        with:
          config-file: |
            .github/labels.json
          clean-labels: true