name: Sync labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/label-syncer.yml

permissions:
  contents: read
  issues: write

jobs:
  labels:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: srealmoreno/label-sync-action@v1
        with:
          clean-labels: true